name: Build binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: devkitpro/devkitppc
    steps:
      - name: Download ppc-libcurl and other deps
        run:  |
          curl https://gitlab.com/4TU/wii-packages/uploads/686f898638fb96af55e3754b92c5aaa7/libwiisocket-0.1-1-any.pkg.tar.zst -o libwiisocket-0.1-1-any.pkg.tar.zst
          curl https://gitlab.com/4TU/wii-packages/uploads/fc3378553929e58a397df6ec6204a1c0/wii-mbedtls-2.16.6-1-any.pkg.tar.zst -o wii-mbedtls-2.16.6-1-any.pkg.tar.zst
          curl https://gitlab.com/4TU/wii-packages/uploads/2b19acc728140dcfbbf7e18f9d9e312a/wii-curl-7.75.0-1-any.pkg.tar.zst -o wii-curl-7.75.0-1-any.pkg.tar.zst
          (dkp-)pacman -U libwiisocket-0.1-1-any.pkg.tar.zst wii-mbedtls-2.16.6-1-any.pkg.tar.zst wii-curl-7.75.0-1-any.pkg.tar.zst
      - uses: actions/checkout@v1
      - name: Build
        run: make
      - name: Package
        run: |
          mkdir -p apps/Mail-Patcher/
          cp Mail-Patcher.dol apps/Mail-Patcher/boot.dol
          cp icon.png apps/Mail-Patcher/icon.png
          cp meta.xml apps/Mail-Patcher/meta.xml
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: Mail-Patcher
          path: apps
